Repository victorusu/gromacs, pull requests merged in 2020-02, with the labels that each got.

#30 Nblib force calculator impl
  src/gromacs/nblib/forcecalculator.cpp
  src/gromacs/nblib/forcecalculator.h
  src/gromacs/nblib/integrator.cpp
  src/gromacs/nblib/nbkerneloptions.cpp
  src/gromacs/nblib/nbkerneloptions.h
  src/gromacs/nblib/nbkernelsystem.cpp
  src/gromacs/nblib/nbkernelsystem.h
  src/gromacs/nblib/simulationstate.cpp
  src/gromacs/nblib/simulationstate.h
  src/gromacs/nblib/tests/nbkernelsystem.cpp
  src/gromacs/nblib/tests/nblib.cpp
  src/gromacs/nblib/tests/topology.cpp
  src/gromacs/nblib/topology.cpp
  src/gromacs/nblib/topology.h
Labels: enhancement

#32 zero init verletForces and multiply C6/12 by 6/12
  src/gromacs/nblib/forcecalculator.cpp
Labels: bug

#39 Separate nbnxm setup from the user code
  src/gromacs/nblib/atoms.cpp
  src/gromacs/nblib/atomtype.h
  src/gromacs/nblib/forcecalculator.cpp
  src/gromacs/nblib/forcecalculator.h
  src/gromacs/nblib/gmxsetup.cpp
  src/gromacs/nblib/gmxsetup.h
  src/gromacs/nblib/simulationstate.cpp
  src/gromacs/nblib/simulationstate.h
  src/gromacs/nblib/tests/CMakeLists.txt
  src/gromacs/nblib/tests/nbkernelsystem.cpp
  src/gromacs/nblib/tests/nbnxnsetup.cpp
Labels: design change, enhancement

#47 Reorganize gmxcalculator
  src/gromacs/nblib/forcecalculator.cpp
  src/gromacs/nblib/forcecalculator.h
  src/gromacs/nblib/gmxcalculator.cpp
  src/gromacs/nblib/gmxcalculator.h
Labels: refactor

#46 Nblib fixes
  src/gromacs/gmxpreprocess/toppush.cpp
  src/gromacs/nblib/particletype.cpp
  src/gromacs/nblib/simulationstate.cpp
  src/gromacs/nblib/tests/testsystems.cpp
  src/gromacs/nblib/tests/topology.cpp
  src/gromacs/nblib/topology.cpp
  src/gromacs/topology/exclusionblocks.cpp
  src/gromacs/topology/exclusionblocks.h
Labels: format, refactor

#53 made bond types work as indices to InteractionTuple
  src/gromacs/nblib/molecules.h
  src/gromacs/nblib/tests/molecules.cpp
  src/gromacs/nblib/util.h
Labels: design change, enhancement

#49 Introduce ParticleTypesInteraction
  src/gromacs/nblib/gmxsetup.cpp
  src/gromacs/nblib/gmxsetup.h
  src/gromacs/nblib/interactions.cpp
  src/gromacs/nblib/interactions.h
  src/gromacs/nblib/nbkerneldef.h
  src/gromacs/nblib/nbkerneloptions.h
  src/gromacs/nblib/particletype.h
Labels: design change, enhancement

#55 [RFC] Made wrapper class for SimulationState
  src/gromacs/nblib/gmxcalculator.cpp
  src/gromacs/nblib/gmxcalculator.h
  src/gromacs/nblib/gmxsetup.cpp
  src/gromacs/nblib/gmxsetup.h
  src/gromacs/nblib/interactions.cpp
  src/gromacs/nblib/simulationstate.cpp
  src/gromacs/nblib/simulationstate.h
Labels: design change, enhancement
