Repository victorusu/gromacs, pull requests merged in 2020-05, with the labels that each got.

#69 Nblib topo interactions
  src/gromacs/nblib/bondtypes.cpp
  src/gromacs/nblib/bondtypes.h
  src/gromacs/nblib/molecules.cpp
  src/gromacs/nblib/molecules.h
  src/gromacs/nblib/ppmap.h
  src/gromacs/nblib/tests/bondtypes.cpp
  src/gromacs/nblib/tests/molecules.cpp
  src/gromacs/nblib/tests/testsystems.cpp
  src/gromacs/nblib/tests/topology.cpp
  src/gromacs/nblib/topology.cpp
  src/gromacs/nblib/topology.h
  src/gromacs/nblib/util.h
Labels: enhancement

#78 Remove unused compareLists function template
  src/gromacs/nblib/tests/nbkernelsystem.cpp
Labels: build errors/warnings, format

#79 Fix integrator test message
  src/gromacs/nblib/tests/integrator.cpp
Labels: bug, build errors/warnings, format
