Repository victorusu/gromacs, pull requests merged in 2020-03, with the labels that each got.

#62 Fix most of the check-source warnings
  src/gromacs/nblib/forcecalculator.cpp
  src/gromacs/nblib/forcecalculator.h
  src/gromacs/nblib/gmxcalculator.cpp
  src/gromacs/nblib/gmxcalculator.h
  src/gromacs/nblib/gmxsetup.cpp
  src/gromacs/nblib/gmxsetup.h
  src/gromacs/nblib/interactions.cpp
  src/gromacs/nblib/interactions.h
  src/gromacs/nblib/particletype.h
  src/gromacs/nblib/tests/testsystems.cpp
  src/gromacs/nblib/tests/testsystems.h
Labels: format

#51 Reorganize GMX Setup Utils
  src/gromacs/nblib/box.cpp
  src/gromacs/nblib/box.h
  src/gromacs/nblib/forcecalculator.cpp
  src/gromacs/nblib/forcecalculator.h
  src/gromacs/nblib/gmxcalculator.cpp
  src/gromacs/nblib/gmxcalculator.h
  src/gromacs/nblib/gmxsetup.cpp
  src/gromacs/nblib/gmxsetup.h
  src/gromacs/nblib/integrator.cpp
  src/gromacs/nblib/simulationstate.cpp
  src/gromacs/nblib/simulationstate.h
  src/gromacs/nblib/tests/gmxcalculator.cpp
  src/gromacs/nblib/tests/nbkernelsystem.cpp
  src/gromacs/nblib/tests/nbnxnsetup.cpp
Labels: refactor

#63 fixed matrix nameclash
  src/gromacs/nblib/box.cpp
  src/gromacs/nblib/box.h
  src/gromacs/nblib/tests/box.cpp
  src/gromacs/nblib/tests/testhelpers.cpp
Labels: bug

#57 [WIP] Add ParticleType interactions into Topology
  src/gromacs/nblib/box.h
  src/gromacs/nblib/forcecalculator.h
  src/gromacs/nblib/gmxsetup.cpp
  src/gromacs/nblib/gmxsetup.h
  src/gromacs/nblib/interactions.cpp
  src/gromacs/nblib/interactions.h
  src/gromacs/nblib/simulationstate.cpp
  src/gromacs/nblib/tests/CMakeLists.txt
  src/gromacs/nblib/tests/forcecalculator.cpp
  src/gromacs/nblib/tests/integrator.cpp
  src/gromacs/nblib/tests/interactions.cpp
  src/gromacs/nblib/tests/molecules.cpp
  src/gromacs/nblib/tests/testsystems.cpp
  src/gromacs/nblib/tests/testsystems.h
  src/gromacs/nblib/topology.cpp
  src/gromacs/nblib/topology.h
Labels: enhancement
